{% set name = "ruptura" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ruptura-{{ version }}.tar.gz
  sha256: 597630fdaf8cc319a9feaebed2cba5fff12c2b6fde16179f56791269dc9f0b9d

build:
  skip: true
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python >=3.8
    - setuptools >=42
    - pybind11 >=2.10.0
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3
    - numpy >=1
    - pybind11 >=2
    - setuptools >=42

test:
  imports:
    - ruptura
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - YouriRan
