{% set name = "ruptura" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ruptura-{{ version }}.tar.gz
  sha256: 25a28cb0773112b1594e04ecb928136945081052ee1d4ee868697c9a36b805d5

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=42
    - pybind11 >=2.10.0
    - pip
  run:
    - python
    - matplotlib-base >=3
    - numpy >=1
    - pybind11 >=2
    - setuptools >=42

test:
  imports:
    - ruptura
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iRASPA/RUPTURA
  summary: "A simulation package to compute breakthrough curves and IAST mixture predictions."
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - YouriRan
